### ISSUE TITLE
Comentarios avance1

### ISSUE THREAD

**Issue by AliciaMstt** [ghuertaramos/ProyectoFinalBioinf2017-II#1]
En el siguiente avance no olvides detallar con qué software(s) y cómo integrarás Maxent.

Hay un curso de R y modelado de nicho que se dará en el congreso mexicano de ecología, quizá te interese

**Comment by AzaleaGuerra** [comment]
¡Se ve padre! No olvides que debes incluir un pequeño set de datos de prueba.

**Comment by ghuertaramos** [comment]
De acuerdo, Muchas gracias.
