### ISSUE TITLE
comentarios avances 2

### ISSUE THREAD

**Issue by AliciaMstt** [ghuertaramos/ProyectoFinalBioinf2017-II#2]
Pinta muy bien tu proyecto y me gustó el diagrama.

Te recomiendo, si es que no lo has hecho ya, tener las funciones en archivos separados que luego llames con source en un sólo script maestro, esto ayuda muchoa a entender el flujo y no perderse.

*Ya pude integrar un par de scripts propios y utilizarlos creando un contenedor, aún falta incluir los demás. Sin embargo, estoy pensando si son demasiadas las funciones que pretendo integrar dentro del mismo contenedor, Probablemente podría realizar un par de contenedores para que sea más simple visualizar lo que hace cada uno y sus resultados.*

Lo dejo a tu consideración, pero pinesa que puedes presentarlo como módulos dentro de un solo contenedor y así con un solo docker pull ya se tiene todo lo necesario para correr los análisis. Además de que sería más fácil correrlo en una sola pipeline. Sólo haría difernetes contenedores si las librerías tuvieran dependencias conflictivas entre sí.

Cuanod dices *También tengo que definir bien cuales son las librerías que necesitan ser incluidas dentro del dockerfile y cuales sólo se pueden instalar fuera de R.* no entiendo a qué te refieres con *fuera de R*.

**Comment by ghuertaramos** [comment]
Gracias por tus comentarios Alicia, los he tomado en cuenta.
En el último punto me refería a las librerías que tienes que ser instaladas sobre la imagen de R-Base al crear el docker file (p. ej. Java, libgeos) que son necesarias para que se pueden instalar algunos paquetes de R. Estama muy mal radactado.
Disculpa que había olvidado cerrar esto.
